### ISSUE TITLE
Installing on mac

### ISSUE THREAD

**Issue by tsbaguley** [brandmaier/onyxR#1]
Looks great but struggled to install on my mac ... probably a stupid error my part.

https:// URLs are not supported by the default method: trying "libcurl"
Downloading git repo https://github.com/brandmaier/onyxR
Installing onyxR
trying URL 'http://cran.uk.r-project.org/bin/macosx/mavericks/contrib/3.2/lavaan_0.5-22'
Content type 'application/x-gzip' length 866130 bytes (845 KB)
==================================================
downloaded 845 KB

Error: Don't know how to decompress files with extension 5-22

**Comment by brandmaier** [comment]
Sorry for the trouble! I haven't seen this error before. The error happens when R tries to install the _lavaan_ package, on which _onyxR_ depends. Have you tried installing _lavaan_ manually beforehands:

`install.packages("lavaan")`

**Comment by tsbaguley** [comment]
I think it is already installed, but I’ll give it another go. Possibly it may be a weird issue with my setup. I’m looking forward to playing with it!

Happy holidays!

Thom

**Comment by tsbaguley** [comment]
Thank you - I now have it installed (lava an was on my work machine but not my home machine for some reason). I just now need to figure out why java isn’t working …

Thom

**Comment by brandmaier** [comment]
Please check whether you can run standalone Onyx (download from http://onyx.brandmaier.de and double-click the *.jar file). Also, please check the installed java version (run the command "java -version"). It need to be version 1.6 or higher.

**Comment by tsbaguley** [comment]
Thanks,

All working now - it looks great!

Thom
